/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author carlo
 */
public class Alerta extends javax.swing.JFrame {

    /**
     * Creates new form Error_1
     */
    public Alerta(int a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(38, 34, 33));
        if (a == 1) {
            jLabel1.setIcon(new ImageIcon("src/Img/Error_1.png"));
        } else if (a == 2) {
            jLabel1.setIcon(new ImageIcon("src/Img/Conexion.png"));
        } else if (a == 3) {
            jLabel1.setIcon(new ImageIcon("src/Img/Error_2.png"));
        } else if (a == 4) {
            jLabel1.setIcon(new ImageIcon("src/Img/Error_3.png"));
        } else if (a == 5) {
            jLabel1.setIcon(new ImageIcon("src/Img/Waiting.png"));
            jLabel2.setVisible(false);
        }
        jLabel2.setIcon(new ImageIcon("src/Img/Close.png"));
    }

    public void TimeOut() {
        jLabel1.setIcon(new ImageIcon("src/Img/Error_2.png"));
        jLabel2.setVisible(true);
    }

    public void Connected() {
        jLabel1.setIcon(new ImageIcon("src/Img/Conexion.png"));
        jLabel2.setVisible(true);
    }

    public Alerta() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(38, 34, 33));
        jLabel2.setIcon(new ImageIcon("src/Img/Close.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 10, 20, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
