package Cliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Frames.Alerta;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author carlo
 */
public class F_sCliente extends javax.swing.JFrame implements Runnable {

    Thread WConnexion;
    Cliente c = new Cliente();

    /**
     * Creates new form Servidor
     */
    public F_sCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(38, 34, 33));
        jLabel1.setIcon(new ImageIcon("src/Img/Logo.png"));
        jLabel2.setIcon(new ImageIcon("src/Img/Conectar_in.png"));
        jLabel3.setIcon(new ImageIcon("src/Img/Close.png"));
    }

    public void Execute() throws IOException {
        WConnexion = new Thread(this);
        WConnexion.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldRound3 = new jtextfieldround.JTextFieldRound();
        jTextFieldRound2 = new jtextfieldround.JPasswordFieldRound();
        jTextFieldRound1 = new jtextfieldround.JTextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRound4 = new jtextfieldround.JTextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 100, 100);

        jTextFieldRound3.setText("Dirección IP");
        jTextFieldRound3.setBackground(new java.awt.Color(38, 34, 33));
        jTextFieldRound3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldRound3.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jTextFieldRound3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRound3.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRound3KeyPressed(evt);
            }
        });
        jTextFieldRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRound3MouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldRound3);
        jTextFieldRound3.setBounds(24, 310, 250, 28);

        jTextFieldRound2.setText("Contraseña");
        jTextFieldRound2.setBackground(new java.awt.Color(38, 34, 33));
        jTextFieldRound2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRound2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRound2KeyPressed(evt);
            }
        });
        jTextFieldRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRound2MouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldRound2);
        jTextFieldRound2.setBounds(24, 260, 250, 28);

        jTextFieldRound1.setText("Usuario");
        jTextFieldRound1.setBackground(new java.awt.Color(38, 34, 33));
        jTextFieldRound1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldRound1.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jTextFieldRound1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRound1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRound1KeyPressed(evt);
            }
        });
        jTextFieldRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRound1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldRound1);
        jTextFieldRound1.setBounds(24, 210, 250, 28);

        jLabel2.setPreferredSize(new java.awt.Dimension(260, 50));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 420, 260, 50);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 10, 20, 20);

        jTextFieldRound4.setText("Puerto");
        jTextFieldRound4.setBackground(new java.awt.Color(38, 34, 33));
        jTextFieldRound4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldRound4.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jTextFieldRound4.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRound4.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldRound4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRound4KeyPressed(evt);
            }
        });
        jTextFieldRound4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRound4MouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldRound4);
        jTextFieldRound4.setBounds(24, 360, 250, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new ImageIcon("src/Img/Conectar_on.png"));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new ImageIcon("src/Img/Conectar_in.png"));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jTextFieldRound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRound1MouseClicked
        if (jTextFieldRound1.getText().equals("Usuario")) {
            jTextFieldRound1.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound1MouseClicked

    private void jTextFieldRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRound3MouseClicked
        if (jTextFieldRound3.getText().equals("Dirección IP")) {
            jTextFieldRound3.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (jTextFieldRound1.getText().equals("") || jTextFieldRound2.getText().equals("") || jTextFieldRound3.getText().equals("")) {
            Alerta exe = new Alerta(1);
            exe.setVisible(true);
        } else {
            try {
                Execute();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        try {
            c.CerrarDatos();        // TODO add your handling code here:
        } catch (IOException ex) {
           System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextFieldRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRound2MouseClicked
        if (jTextFieldRound2.getText().equals("Contraseña")) {
            jTextFieldRound2.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound2MouseClicked

    private void jTextFieldRound1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRound1KeyPressed
        if (jTextFieldRound1.getText().equals("Usuario")) {
            jTextFieldRound1.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound1KeyPressed

    private void jTextFieldRound2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRound2KeyPressed
        if (jTextFieldRound2.getText().equals("Contraseña")) {
            jTextFieldRound2.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound2KeyPressed

    private void jTextFieldRound3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRound3KeyPressed
        if (jTextFieldRound3.getText().equals("Dirección IP")) {
            jTextFieldRound3.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound3KeyPressed

    private void jTextFieldRound4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRound4KeyPressed
        if (jTextFieldRound4.getText().equals("Puerto")) {
            jTextFieldRound4.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound4KeyPressed

    private void jTextFieldRound4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRound4MouseClicked
        if (jTextFieldRound4.getText().equals("Puerto")) {
            jTextFieldRound4.setText("");
        }
    }//GEN-LAST:event_jTextFieldRound4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        F_sCliente r = new F_sCliente();
        r.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private jtextfieldround.JTextFieldRound jTextFieldRound1;
    private jtextfieldround.JPasswordFieldRound jTextFieldRound2;
    private jtextfieldround.JTextFieldRound jTextFieldRound3;
    private jtextfieldround.JTextFieldRound jTextFieldRound4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Alerta a = new Alerta(5);
        this.setEnabled(false);
        a.setVisible(true);
        try {
            if (c.isConnected(jTextFieldRound3.getText(), Integer.parseInt(jTextFieldRound4.getText()),jTextFieldRound1.getText()+":"+jTextFieldRound2.getText())) {
                System.out.println("entro");
                a.Connected();
                dispose();
                F_Cliente f = new F_Cliente(jTextFieldRound3.getText(), Integer.parseInt(jTextFieldRound4.getText()));
                f.setVisible(true);
            } else {
                a.TimeOut();
                this.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(F_sCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(F_sCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
